[package]
name = "gkl-agent"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
gkl-git = { path = "../gkl-git" }
gkl-db = { path = "../gkl-db" }
gkl-core = { path = "../gkl-core" }
anyhow = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
ureq = { workspace = true }
